/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facility/{facility_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facility */
        get: operations["facility_api_facility__facility_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/desert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Desert */
        get: operations["desert_api_desert_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trace/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace */
        get: operations["trace_api_trace__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Scenarios */
        get: operations["demo_scenarios_api_demo_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CapabilityClaim
         * @description One row per (facility, capability). The atomic unit of trust.
         */
        CapabilityClaim: {
            /** Capability */
            capability: string;
            /** Claim Present */
            claim_present: boolean;
            /** Self Consistency Score */
            self_consistency_score: number;
            /** Coherence Score */
            coherence_score: number;
            /** Peer Anomaly Score */
            peer_anomaly_score: number;
            /** Trust Score */
            trust_score: number;
            /** Confidence Interval Low */
            confidence_interval_low: number;
            /** Confidence Interval High */
            confidence_interval_high: number;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Flags */
            flags?: string[];
        };
        /**
         * Citation
         * @description Exact provenance for any extracted fact.
         */
        Citation: {
            /** Source Field */
            source_field: string;
            /** Sentence */
            sentence: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /** DemoScenario */
        DemoScenario: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            request: components["schemas"]["QueryRequest"];
        };
        /** DemoScenariosResponse */
        DemoScenariosResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["DemoScenario"][];
        };
        /**
         * FacilityTrustRecord
         * @description One row per facility in `gold.facility_trust`.
         */
        FacilityTrustRecord: {
            /** Facility Id */
            facility_id: string;
            /** Facility Name */
            facility_name: string;
            /** Pin Code */
            pin_code: string;
            /** State */
            state: string;
            /** District */
            district: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Facility Type */
            facility_type: string;
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityClaim"][];
            /** Overall Trust Score */
            overall_trust_score: number;
            /** Extraction Run Ids */
            extraction_run_ids: string[];
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "real";
        };
        /**
         * PinCodeDesert
         * @description One row per (pin_code, capability) in `gold.pin_code_desert`.
         */
        PinCodeDesert: {
            /** Pin Code */
            pin_code: string;
            /** State */
            state: string;
            /** District */
            district: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Population */
            population?: number | null;
            /** Capability */
            capability: string;
            /** Nearest Verified Facility Id */
            nearest_verified_facility_id?: string | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Desert Score */
            desert_score: number;
        };
        /**
         * QueryRequest
         * @description User query into the Coordinator agent.
         */
        QueryRequest: {
            /** Text */
            text: string;
            /** User Lat */
            user_lat?: number | null;
            /** User Lon */
            user_lon?: number | null;
            /** Max Distance Km */
            max_distance_km?: number | null;
            /**
             * Min Trust Score
             * @default 0.5
             */
            min_trust_score: number;
            /** Capabilities Filter */
            capabilities_filter?: string[] | null;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /**
         * QueryResponse
         * @description The thing the (eventual) frontend renders.
         */
        QueryResponse: {
            /** Query */
            query: string;
            /** Candidates */
            candidates: components["schemas"]["FacilityTrustRecord"][];
            /** Citations Per Candidate */
            citations_per_candidate: {
                [key: string]: components["schemas"]["Citation"][];
            };
            /**
             * Critic Verdict
             * @enum {string}
             */
            critic_verdict: "supported" | "partial" | "unsupported";
            /** Critic Reasoning */
            critic_reasoning: string;
            /** Trace Id */
            trace_id: string;
        };
        /** TraceResponse */
        TraceResponse: {
            /** Trace Id */
            trace_id: string;
            /** Found */
            found: boolean;
            /** Spans */
            spans: components["schemas"]["TraceSpan"][];
        };
        /** TraceSpan */
        TraceSpan: {
            /** Name */
            name: string;
            /** Span Type */
            span_type?: string | null;
            /** Start Time Ms */
            start_time_ms?: number | null;
            /** End Time Ms */
            end_time_ms?: number | null;
            /**
             * Attributes
             * @default {}
             */
            attributes: {
                [key: string]: string | number | boolean | null;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facility_api_facility__facility_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityTrustRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desert_api_desert_get: {
        parameters: {
            query?: {
                capability?: string | null;
                state?: string | null;
                pin_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinCodeDesert"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_api_trace__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_scenarios_api_demo_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoScenariosResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
