/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facility/{facility_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facility */
        get: operations["facility_api_facility__facility_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facility/{facility_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_facility__facility_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/desert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Desert */
        get: operations["desert_api_desert_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/desert/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_desert_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trace/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace */
        get: operations["trace_api_trace__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trace/{trace_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_trace__trace_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Scenarios */
        get: operations["demo_scenarios_api_demo_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-moments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Moments */
        get: operations["demo_moments_api_demo_moments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frontend-contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frontend Contract */
        get: operations["frontend_contract_api_frontend_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_portal_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/register/{registration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registration Status */
        get: operations["registration_status_portal_register__registration_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_portal_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_portal_token_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/admin/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Registrations */
        get: operations["list_registrations_portal_admin_registrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/admin/registrations/{registration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Registration */
        patch: operations["review_registration_portal_admin_registrations__registration_id__patch"];
        trace?: never;
    };
    "/portal/facility/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facility Me */
        get: operations["facility_me_portal_facility_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/facility/me/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facility Score */
        get: operations["facility_score_portal_facility_me_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Update Requests */
        get: operations["list_update_requests_portal_updates_get"];
        put?: never;
        /** Create Update Request */
        post: operations["create_update_request_portal_updates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/updates/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Update Request */
        get: operations["get_update_request_portal_updates__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/admin/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Updates */
        get: operations["list_admin_updates_portal_admin_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/admin/updates/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Update Request */
        patch: operations["review_update_request_portal_admin_updates__request_id__patch"];
        trace?: never;
    };
    "/portal/proof/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Proof */
        post: operations["upload_proof_portal_proof_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/proof/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proof Metadata */
        get: operations["proof_metadata_portal_proof__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/admin/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proof Media */
        get: operations["list_proof_media_portal_admin_proof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/admin/proof/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Proof Metadata */
        get: operations["admin_proof_metadata_portal_admin_proof__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal/admin/proof/{media_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Proof File */
        get: operations["admin_proof_file_portal_admin_proof__media_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_proof_portal_proof_upload_post */
        Body_upload_proof_portal_proof_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Location Lat */
            location_lat: number;
            /** Location Lon */
            location_lon: number;
            /** Location Accuracy M */
            location_accuracy_m: number;
            /**
             * Location Captured At
             * Format: date-time
             */
            location_captured_at: string;
            /** Update Request Id */
            update_request_id?: string | null;
        };
        /**
         * CapabilityClaim
         * @description One row per (facility, capability). The atomic unit of trust.
         */
        CapabilityClaim: {
            /** Capability */
            capability: string;
            /** Claim Present */
            claim_present: boolean;
            /** Self Consistency Score */
            self_consistency_score: number;
            /** Coherence Score */
            coherence_score: number;
            /** Peer Anomaly Score */
            peer_anomaly_score: number;
            /** Trust Score */
            trust_score: number;
            /** Confidence Interval Low */
            confidence_interval_low: number;
            /** Confidence Interval High */
            confidence_interval_high: number;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Flags */
            flags?: string[];
        };
        /** CapabilityDashboardRow */
        CapabilityDashboardRow: {
            /** Capability */
            capability: string;
            /** Label */
            label: string;
            /** Trust Score Percent */
            trust_score_percent: number;
            /** Claim Present */
            claim_present: boolean;
            /** Status Label */
            status_label: string;
            /** Explanation */
            explanation: string;
            /** Citation Sentence */
            citation_sentence?: string | null;
            /** Flags */
            flags?: string[];
            /** Plain English Flags */
            plain_english_flags?: string[];
        };
        /**
         * Citation
         * @description Exact provenance for any extracted fact.
         */
        Citation: {
            /** Source Field */
            source_field: string;
            /** Sentence */
            sentence: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /** DemoMoment */
        DemoMoment: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Endpoint */
            endpoint: string;
            request?: components["schemas"]["QueryRequest"] | null;
            /** Target Facility Id */
            target_facility_id?: string | null;
            /** Target Pin Code */
            target_pin_code?: string | null;
            /** Expected Flag */
            expected_flag?: string | null;
            /** Success Criteria */
            success_criteria: string[];
            /** Design Notes */
            design_notes: string[];
        };
        /** DemoMomentsResponse */
        DemoMomentsResponse: {
            /** Moments */
            moments: components["schemas"]["DemoMoment"][];
        };
        /** DemoScenario */
        DemoScenario: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            request: components["schemas"]["QueryRequest"];
        };
        /** DemoScenariosResponse */
        DemoScenariosResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["DemoScenario"][];
        };
        /** DesertGroupSummary */
        DesertGroupSummary: {
            /** Key */
            key: string;
            /** Row Count */
            row_count: number;
            /** Critical Pin Count */
            critical_pin_count: number;
            /** Population At Risk */
            population_at_risk: number;
            /** Average Desert Score */
            average_desert_score: number;
        };
        /** DesertPinSummary */
        DesertPinSummary: {
            /** Pin Code */
            pin_code: string;
            /** State */
            state: string;
            /** District */
            district: string;
            /** Capability */
            capability: string;
            /** Population */
            population?: number | null;
            /** Desert Score */
            desert_score: number;
            /** Nearest Verified Facility Id */
            nearest_verified_facility_id?: string | null;
            /** Distance Km */
            distance_km?: number | null;
        };
        /** DesertSummary */
        DesertSummary: {
            /** Capability */
            capability?: string | null;
            /** State */
            state?: string | null;
            /** Total Rows */
            total_rows: number;
            /** Critical Pin Count */
            critical_pin_count: number;
            /** Population At Risk */
            population_at_risk: number;
            /** Average Desert Score */
            average_desert_score: number;
            /** Top Deserts */
            top_deserts: components["schemas"]["DesertPinSummary"][];
            /** By State */
            by_state: components["schemas"]["DesertGroupSummary"][];
            /** By Capability */
            by_capability: components["schemas"]["DesertGroupSummary"][];
        };
        /** EndpointContract */
        EndpointContract: {
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST";
            /** Path */
            path: string;
            /** Purpose */
            purpose: string;
            /** Response Model */
            response_model: string;
            /** Notes */
            notes?: string[];
        };
        /** EvidenceSnippet */
        EvidenceSnippet: {
            /** Facility Id */
            facility_id: string;
            /** Capability */
            capability: string;
            /** Source Field */
            source_field: string;
            /** Sentence */
            sentence: string;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Flags */
            flags?: string[];
        };
        /** FacilityDashboardResponse */
        FacilityDashboardResponse: {
            /** Facility Id */
            facility_id: string;
            /** Facility Name */
            facility_name: string;
            /** Pin Code */
            pin_code: string;
            /** State */
            state: string;
            /** District */
            district: string;
            /** Facility Type */
            facility_type: string;
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
            /** Trust Score Percent */
            trust_score_percent: number;
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityDashboardRow"][];
            /** Update Requests */
            update_requests?: components["schemas"]["UpdateRequest"][];
            /** Improvement Suggestions */
            improvement_suggestions?: components["schemas"]["ImprovementSuggestion"][];
        };
        /** FacilityEvidenceResponse */
        FacilityEvidenceResponse: {
            /** Facility Id */
            facility_id: string;
            /** Facility Name */
            facility_name: string;
            /** Pin Code */
            pin_code: string;
            /** State */
            state: string;
            /** District */
            district: string;
            /** Facility Type */
            facility_type: string;
            /** Overall Trust Score */
            overall_trust_score: number;
            /** Has Flags */
            has_flags: boolean;
            /** Flags */
            flags: string[];
            /** Flag Summary */
            flag_summary?: string | null;
            /** Signals */
            signals: components["schemas"]["SignalBreakdown"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceSnippet"][];
            /** Audit Summary */
            audit_summary: string;
        };
        /**
         * FacilityRegistration
         * @description A hospital or clinic's application to join the portal.
         */
        FacilityRegistration: {
            /** Registration Id */
            registration_id: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Facility Name */
            facility_name: string;
            /** Facility Type */
            facility_type: string;
            /** Official Phone */
            official_phone: string;
            /** Official Email */
            official_email: string;
            /** Official Website */
            official_website?: string | null;
            /** Address Line1 */
            address_line1: string;
            /** Address Line2 */
            address_line2?: string | null;
            /** Address City */
            address_city: string;
            /** Address State Or Region */
            address_state_or_region: string;
            /** Address Zip Or Postcode */
            address_zip_or_postcode: string;
            /**
             * Address Country
             * @default India
             */
            address_country: string;
            /** Contact Person Name */
            contact_person_name: string;
            /** Contact Person Role */
            contact_person_role: string;
            /** Contact Person Phone */
            contact_person_phone: string;
            /** Contact Person Email */
            contact_person_email: string;
            /** Proof Documents */
            proof_documents?: string[];
            /** Matched Facility Id */
            matched_facility_id?: string | null;
            /** Match Confidence */
            match_confidence?: number | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "under_review" | "approved" | "rejected" | "needs_more_info";
            /** Reviewer Notes */
            reviewer_notes?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Portal User Id */
            portal_user_id?: string | null;
            /** Portal Access Token Hash */
            portal_access_token_hash?: string | null;
        };
        /**
         * FacilityTrustRecord
         * @description One row per facility in `gold.facility_trust`.
         */
        FacilityTrustRecord: {
            /** Facility Id */
            facility_id: string;
            /** Facility Name */
            facility_name: string;
            /** Pin Code */
            pin_code: string;
            /** State */
            state: string;
            /** District */
            district: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Facility Type */
            facility_type: string;
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityClaim"][];
            /** Overall Trust Score */
            overall_trust_score: number;
            /** Extraction Run Ids */
            extraction_run_ids: string[];
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /** FrontendContractResponse */
        FrontendContractResponse: {
            /** Product Name */
            product_name: string;
            /** Frontend Owner */
            frontend_owner: string;
            /** Backend Owner */
            backend_owner: string;
            /** Constraints */
            constraints: string[];
            /** Endpoints */
            endpoints: components["schemas"]["EndpointContract"][];
            /** Demo Sequence */
            demo_sequence: string[];
            /** Field Notes */
            field_notes: {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "real";
        };
        /** ImprovementSuggestion */
        ImprovementSuggestion: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low";
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Field Name */
            field_name?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PinCodeDesert
         * @description One row per (pin_code, capability) in `gold.pin_code_desert`.
         */
        PinCodeDesert: {
            /** Pin Code */
            pin_code: string;
            /** State */
            state: string;
            /** District */
            district: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Population */
            population?: number | null;
            /** Capability */
            capability: string;
            /** Nearest Verified Facility Id */
            nearest_verified_facility_id?: string | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Desert Score */
            desert_score: number;
        };
        /**
         * ProofMedia
         * @description A photo or document uploaded as proof for an update request.
         */
        ProofMedia: {
            /** Media Id */
            media_id: string;
            /** Update Request Id */
            update_request_id?: string | null;
            /** Facility Id */
            facility_id: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Storage Path */
            storage_path: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Location Lat */
            location_lat?: number | null;
            /** Location Lon */
            location_lon?: number | null;
            /** Location Accuracy M */
            location_accuracy_m?: number | null;
            /** Location Captured At */
            location_captured_at?: string | null;
            /** Exif Datetime */
            exif_datetime?: string | null;
            /** Exif Gps Lat */
            exif_gps_lat?: number | null;
            /** Exif Gps Lon */
            exif_gps_lon?: number | null;
            /** Exif Device Model */
            exif_device_model?: string | null;
            /**
             * Location Discrepancy Detected
             * @default false
             */
            location_discrepancy_detected: boolean;
            /**
             * Timestamp Discrepancy Detected
             * @default false
             */
            timestamp_discrepancy_detected: boolean;
            /**
             * Location Verified
             * @default false
             */
            location_verified: boolean;
            /**
             * Content Verified
             * @default false
             */
            content_verified: boolean;
            /** Reviewer Notes */
            reviewer_notes?: string | null;
        };
        /**
         * QueryRequest
         * @description User query into the Coordinator agent.
         */
        QueryRequest: {
            /** Text */
            text: string;
            /** User Lat */
            user_lat?: number | null;
            /** User Lon */
            user_lon?: number | null;
            /** Max Distance Km */
            max_distance_km?: number | null;
            /**
             * Min Trust Score
             * @default 0.5
             */
            min_trust_score: number;
            /** Capabilities Filter */
            capabilities_filter?: string[] | null;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /**
         * QueryResponse
         * @description The thing the (eventual) frontend renders.
         */
        QueryResponse: {
            /** Query */
            query: string;
            /** Candidates */
            candidates: components["schemas"]["FacilityTrustRecord"][];
            /** Citations Per Candidate */
            citations_per_candidate: {
                [key: string]: components["schemas"]["Citation"][];
            };
            /**
             * Critic Verdict
             * @enum {string}
             */
            critic_verdict: "supported" | "partial" | "unsupported";
            /** Critic Reasoning */
            critic_reasoning: string;
            /** Trace Id */
            trace_id: string;
        };
        /** RegistrationCreate */
        RegistrationCreate: {
            /** Facility Name */
            facility_name: string;
            /** Facility Type */
            facility_type: string;
            /** Official Phone */
            official_phone: string;
            /** Official Email */
            official_email: string;
            /** Official Website */
            official_website?: string | null;
            /** Address Line1 */
            address_line1: string;
            /** Address Line2 */
            address_line2?: string | null;
            /** Address City */
            address_city: string;
            /** Address State Or Region */
            address_state_or_region: string;
            /** Address Zip Or Postcode */
            address_zip_or_postcode: string;
            /** Contact Person Name */
            contact_person_name: string;
            /** Contact Person Role */
            contact_person_role: string;
            /** Contact Person Phone */
            contact_person_phone: string;
            /** Contact Person Email */
            contact_person_email: string;
            /** Proof Documents */
            proof_documents?: string[];
            /** Declaration Confirmed */
            declaration_confirmed: boolean;
        };
        /** RegistrationCreateResponse */
        RegistrationCreateResponse: {
            /** Registration Id */
            registration_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "under_review" | "approved" | "rejected" | "needs_more_info";
            /** Matched Facility Id */
            matched_facility_id?: string | null;
            /** Match Confidence */
            match_confidence?: number | null;
        };
        /** RegistrationReviewRequest */
        RegistrationReviewRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "rejected" | "needs_more_info" | "under_review";
            /** Matched Facility Id */
            matched_facility_id?: string | null;
            /** Reviewer Notes */
            reviewer_notes?: string | null;
            /** Temporary Password */
            temporary_password?: string | null;
        };
        /** SignalBreakdown */
        SignalBreakdown: {
            /** Capability */
            capability: string;
            /** Claim Present */
            claim_present: boolean;
            /** Self Consistency Score */
            self_consistency_score: number;
            /** Coherence Score */
            coherence_score: number;
            /** Peer Anomaly Score */
            peer_anomaly_score: number;
            /** Trust Score */
            trust_score: number;
            /** Confidence Interval Low */
            confidence_interval_low: number;
            /** Confidence Interval High */
            confidence_interval_high: number;
            /** Confidence Interval Width */
            confidence_interval_width: number;
            /** Flags */
            flags?: string[];
            /** Citation Count */
            citation_count: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Facility Id */
            facility_id: string;
            /** User Id */
            user_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "facility_admin" | "facility_viewer";
        };
        /** TraceResponse */
        TraceResponse: {
            /** Trace Id */
            trace_id: string;
            /** Found */
            found: boolean;
            /** Spans */
            spans: components["schemas"]["TraceSpan"][];
        };
        /** TraceSpan */
        TraceSpan: {
            /** Name */
            name: string;
            /** Span Type */
            span_type?: string | null;
            /** Start Time Ms */
            start_time_ms?: number | null;
            /** End Time Ms */
            end_time_ms?: number | null;
            /** Attributes */
            attributes?: {
                [key: string]: string | number | boolean | null;
            };
        };
        /** TraceTimelineNode */
        TraceTimelineNode: {
            /** Id */
            id: string;
            /** Agent */
            agent: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "partial" | "unsupported" | "complete" | "unknown";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Token Count */
            token_count?: number | null;
            /** Summary */
            summary: string;
            /** Detail */
            detail?: string | null;
            /** Attributes */
            attributes?: {
                [key: string]: string | number | boolean | null;
            };
        };
        /** TraceTimelineResponse */
        TraceTimelineResponse: {
            /** Trace Id */
            trace_id: string;
            /** Found */
            found: boolean;
            /** Nodes */
            nodes: components["schemas"]["TraceTimelineNode"][];
        };
        /**
         * UpdateRequest
         * @description A verified facility's request to update one field in their record.
         */
        UpdateRequest: {
            /** Request Id */
            request_id: string;
            /** Facility Id */
            facility_id: string;
            /** Portal User Id */
            portal_user_id: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Field Name */
            field_name: string;
            /**
             * Field Category
             * @enum {string}
             */
            field_category: "contact" | "address" | "profile" | "operational" | "clinical" | "equipment" | "capability";
            /** Old Value */
            old_value?: string | null;
            /** New Value */
            new_value: string;
            /** Justification */
            justification: string;
            /** Requires Proof */
            requires_proof: boolean;
            /** Proof Media Ids */
            proof_media_ids?: string[];
            /**
             * Location Verified
             * @default false
             */
            location_verified: boolean;
            /** Proof Location Lat */
            proof_location_lat?: number | null;
            /** Proof Location Lon */
            proof_location_lon?: number | null;
            /** Proof Location Accuracy M */
            proof_location_accuracy_m?: number | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "under_review" | "approved" | "rejected" | "needs_more_info";
            /** Reviewer Notes */
            reviewer_notes?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /**
             * Applied To Pipeline
             * @default false
             */
            applied_to_pipeline: boolean;
            /** Applied At */
            applied_at?: string | null;
            /** Resulting Extraction Run Id */
            resulting_extraction_run_id?: string | null;
        };
        /** UpdateRequestCreate */
        UpdateRequestCreate: {
            /** Field Name */
            field_name: string;
            /** New Value */
            new_value: unknown;
            /** Justification */
            justification: string;
            /** Proof Media Ids */
            proof_media_ids?: string[];
            /** Old Value */
            old_value?: unknown | null;
        };
        /** UpdateReviewRequest */
        UpdateReviewRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "rejected" | "needs_more_info" | "under_review";
            /** Reviewer Notes */
            reviewer_notes?: string | null;
            /**
             * Proof Verified
             * @default false
             */
            proof_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facility_api_facility__facility_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityTrustRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_facility__facility_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityEvidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desert_api_desert_get: {
        parameters: {
            query?: {
                capability?: string | null;
                state?: string | null;
                pin_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinCodeDesert"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_desert_summary_get: {
        parameters: {
            query?: {
                capability?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesertSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_api_trace__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_trace__trace_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_scenarios_api_demo_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoScenariosResponse"];
                };
            };
        };
    };
    demo_moments_api_demo_moments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoMomentsResponse"];
                };
            };
        };
    };
    frontend_contract_api_frontend_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontendContractResponse"];
                };
            };
        };
    };
    register_portal_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registration_status_portal_register__registration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityRegistration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_portal_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_portal_token_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    list_registrations_portal_admin_registrations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityRegistration"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_registration_portal_admin_registrations__registration_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityRegistration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facility_me_portal_facility_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityDashboardResponse"];
                };
            };
        };
    };
    facility_score_portal_facility_me_score_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityDashboardResponse"];
                };
            };
        };
    };
    list_update_requests_portal_updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequest"][];
                };
            };
        };
    };
    create_update_request_portal_updates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_update_request_portal_updates__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_updates_portal_admin_updates_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_update_request_portal_admin_updates__request_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_proof_portal_proof_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_proof_portal_proof_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProofMedia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proof_metadata_portal_proof__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProofMedia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proof_media_portal_admin_proof_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProofMedia"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_proof_metadata_portal_admin_proof__media_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProofMedia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_proof_file_portal_admin_proof__media_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
